name: 'ECS Restart Service'
description: 'Restart an ECS service without code changes'
author: 'Apideck'
branding:
  icon: 'arrow-up'
  color: 'purple'
inputs:
  service:
    required: true
    description: 'The name of the service to update.'
  cluster:
    required: false
    description: 'The short name or full Amazon Resource Name (ARN) of the cluster that your service runs on. If you do not specify a cluster, the default cluster is assumed.'
  force-new-deployment:
    required: false
    description: "Determines whether to force a new deployment of the service. You can use this option to start a new deployment with no service definition changes. For example, you can update a service's tasks to use a newer Docker image with the same image/tag combination (my_image:latest ) or to roll Fargate tasks onto a newer platform version."
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/index.js'
